### ISSUE TITLE
hipdog.jpg violates license

### ISSUE THREAD

**Issue by martey** [emre/macster#4]
The included image [hipdog.jpg](https://github.com/emre/macster/blob/master/hipdog.jpg) seems to be derived by [Paul Lovine's photo of his dog Nickel](https://secure.flickr.com/photos/lovine/5433988749/). According to Flickr, that photo is licensed under a [Creative Commons BY-NC-ND license](https://creativecommons.org/licenses/by-nc-nd/2.0/deed.en). The image should either be removed or replaced with the original work and properly attributed.

**Comment by emre** [comment]
:+1: 

is it okay now?
